pipeline:
  build:
    image: python:2.7
    commands:
      - pip install -r test_requirements.txt
      - scripts/ci/test.sh

  notify:
    image: 258875347723.dkr.ecr.us-east-1.amazonaws.com/drone-plugin-slack
    channel: infra-salon
    secrets: [ slack_webhook ]
    when:
      event: [ push ]
      branch: master
      status: [ success, failure ]

secrets:
  slack_webhook:
    driver: vault
    driver_opts:
      path: secret/drone/common/slack_webhook
